# embed_file(<input> <output.cpp> <symbol>): writes a C++ source that defines
#   extern const unsigned char <symbol>[];  extern const unsigned int <symbol>_size;
# with the bytes of <input>. Runs at configure time; CMake re-runs when the input changes.
function(embed_file input output symbol)
    file(READ "${input}" hex HEX)
    string(LENGTH "${hex}" hex_length)
    math(EXPR size "${hex_length} / 2")
    string(REPEAT "[0-9a-f]" 48 line_pattern)
    string(REGEX REPLACE "(${line_pattern})" "\\1\n" hex "${hex}")
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    file(WRITE "${output}.tmp"
        "// Generated by cmake/embed.cmake from ${input}\n"
        "extern const unsigned char ${symbol}[];\n"
        "extern const unsigned int ${symbol}_size;\n"
        "alignas(4) const unsigned char ${symbol}[] = {\n${bytes}\n};\n"
        "const unsigned int ${symbol}_size = ${size};\n")
    configure_file("${output}.tmp" "${output}" COPYONLY)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${input}")
endfunction()
